; PlatformIO Project Configuration File

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.12/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem2101
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit GC9A01A
    adafruit/Adafruit BusIO
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    '-DWIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'
    '-DMQTT_SERVER="${sysenv.MQTT_SERVER}"'
    '-DMQTT_PORT=${sysenv.MQTT_PORT}'
    '-DMQTT_USER="${sysenv.MQTT_USER}"'
    '-DMQTT_PASSWORD="${sysenv.MQTT_PASSWORD}"'
